### ISSUE TITLE
Suggestion: Support changing the return query of save-form

### ISSUE THREAD

**Issue by eoogbe** [fulcrologic/fulcro-rad#100]
For example, say you're making a signup form that takes in a password. You may want to save the password in the database as a hash. With the current implementation, that password hash will be sent back to the client into the password field. If there was a way to change the return query from save-form to exclude certain attributes, this problem wouldn't occur. Something like:

```
(defsc SignupResult [_this _props]
  {:query [::account/email ::account/id ::account/username]
   :ident ::account/id})

(defsc-form Signup [_this _props]
  {fo/attributes [account/email account/username account/password account/password-confirmation]
   fo/id account/id
   fo/returning SignupResult})
```

And then the handler for `:event/save` can check if returning is defined, otherwise it defaults to the form class.

Just a suggestion. My workaround has been to make a custom machine.

**Comment by awkay** [comment]
I have numerous things to say about this, but the solution is not going to be such a statement on the form macro. Too easy to get out of sync and make a mess.

You're talking about security, and the proper solution is as follows:

1. For sensitive info, don't use a RAD form to begin with. Session management is complicated, and you're better off with a standard `defsc`. If you cannot *actually edit* the info in question, it doesn't belong in a RAD form.
2. Login is *not* a RAD form. Not just because of (1), but because it contains *no* info you want to save. Login is a defsc with a custom UISM completely separate from the base RAD libraries. You might write a reusable thing for it, but it just isn't a RAD form.
3. If there is data that should *never* go on the wire, then it is your responsibility on the *back end* to secure it. Security isn't in the purview of the RAD libraries, because it is too much of a large/moving target. I implemented a few "demo" kinds of things to give you the idea, but *never* treat the core RAD libraries as a source for security. 

In all of my production software that uses RAD I've had to write security layers. You will have to as well.

I suggest using the `wrap-resolve` feature (if using Datomic) to add general security to the generated resolvers if you do want them in a case like this. It is possible to secure them correctly that way, and you will want that for all resolvers in general. You can also choose to hand-write the resolver for things that might be ultra-sensitive and just skip auto-gen for that particular thing.

For hand-written resolvers you're going to need additional security layers. Just saying "I don't ask for sensitive data" is not security. That's like saying "I write my password down on sticky notes, but I keep them in my desk drawer".
