### ISSUE TITLE
Local reporting

### ISSUE THREAD

**Issue by chrismurrph** [fulcrologic/fulcro-rad#44]
Currently RAD reports is 'remote only'. The entities being shown can only come from a remote (`::report/source-attribute`), and there is a noticeable delay. There are times when the entities are in app state, and times when they are in app state but a more recent version needs to be fetched from the remote. So the proposal is to have a new optional tri-state option `::report/source-location`, with possible values `:remote-only`, `:local-only` and `:local-and-remote`. When `::report/source-location` is not specified the default of `:remote-only` is used, which is the current behaviour. For `:local-only` and `:local-and-remote` an additional option `::report/source-table` will be required.

It should be noted that in the private implementation I've done `:local-and-remote` doesn't do too much work - there will only be one circumstance when the filtering, sorting etc pipeline is done twice (once for local and once for remote) - that's when `:raw-rows` is empty. So after the first time the report is viewed the behaviour/performance is the same as it always has been.  

With this implementation `::report/source-attribute` is for getting data from the remote and `::report/source-table` is for getting data locally. So there's a temptation to rename them. Leave them as they are??

**Comment by awkay** [comment]
So there is a wider long-term view than this: federated data. Data can potentially come from *any number* of data sources: local, from different servers, etc. Each *attribute* specifies a data source, and the intention is to build a client adapter that figures all that out and multiplexes it for you (issuing queries to all data sources, merging it all back together, and making it look like a single unified response).

So, I'm concerned about adding something that treats what I essentially see as "the cache" (app db) as a special case that requires extra config.

If the data is already in app state there are two possibilities:

* it is already in the proper shape, and all you want to do is link it in (I think this will be less common, but possible...esp when re-routing to the same report again)
* you need to do some work to morph what you have into a shape the report could use.

In the former case, you probably already used the report to load it. The data is already there and in the right shape. Turning off auto-load should "just work"...well, sort of: the HTML5 (or route) parameters might be a mismatch on the cached data, so in fact the only way to MAKE it consistent is to re-run SOME kind of logic to verify things are OK.

So, in that case, I think *both* cases need something they can run on entry when "auto run" the remote is false.

My inclination that the right thing to do is add a "remote" that uses a client-side pathom parser and the Fulcro db as the data source, so you can write the reshaping in a concise manner. In that case, all you really need is a way to tell the report "use the remote named X".

Of course, the federated bits I mentioned should really be a part of this whole story.

So, at the moment, I'm going to recommend you make your own `defreport-local` macro that does what you want. I'm just not ready to add this kind of thing to the core library.

If what you really want is just the option for a route to a report that is already populated to honor the raw rows and just run filtering/sorting/paginate based on URL parameters, then I'd ask you to analyze what else would be needed to ensure that the result is going to be "correct"?  I think basically the "old params" that were used to load the data that is there would have to be saved somewhere, so that they could be checked against the new incoming params.

**Comment by chrismurrph** [comment]
For my case I could have turned off auto-load, loading manually, and loaded the report before the user ever routed to it. That would have been a way of getting round the lag problem, which only occurs on first click of 'view all'. (Still, hardly a great solution - using what has already been loaded is scalable for lots of reports that all might need to use the same static data). Using a 'local remote' did seem like a stretch too far. But in retrospect would have been the best way to proceed?? And is how I'll refactor this code, sometime many months from now...

**Comment by awkay** [comment]
honestly I don't have a bunch of time to think about it carefully...what you're suggesting might be sane, I just don't have the time to go into library design mode.
