### ISSUE TITLE
Reuse Fulcro's global-eql-transform

### ISSUE THREAD

**Issue by holyjak** [fulcrologic/fulcro-rad#63]
... instead of completely overriding it. And simplify RAD's after fulcrologic/fulcro#484 is resolved.

**Comment by holyjak** [comment]
NOTE: While in Fulcro we do not want to apply ellision to mutation params (as the user is unlikely to *accidentally* include any of the ellided stuff there and might want to include it on purpose, e.g. to send something through params there and back, e.g. ASM id), here it is RAD itself sending the props to mutations and we know we don't want the elided stuff (here RAD is the "user").

**Comment by awkay** [comment]
Since this is a breaking change to RAD itself, and you can set it manually, I'm not sure there's really anything to do here. I guess I could make a new app constructor function that uses new settings, in which case I'd probably want to refine some other things as well. At some point if that becomes compelling enough I'll do it, but after a year of this being open no one really seems much to care?
