### ISSUE TITLE
restore-route! doesn't work on the homepage

### ISSUE THREAD

**Issue by eoogbe** [fulcrologic/fulcro-rad#99]
I'm not sure if this is WAI but `url->route` will return `[]` on the homepage. However, route segments must have at least one string. That means at best the homepage can use the route segment `[""]`. But doing that means `restore-route!` never gets there. IMO it's a bug for `url->route` to return routes that aren't even possible to construct.

**Comment by awkay** [comment]
Not sure how you expect this to work.  That function is used to recover the Fulcro path info using a URL, but the URL MUST, by definition, have something besides "/" in the URI for it to *be* a valid route. E.g. the startup of your app must take care of this because that function cannot know what your "ultimate default route" is for such a URI (in Fulcro's dynamic routing there is *no such thing* as "/", since that doesn't indicate any particular target).

The idea is that your startup code, when seeing "/" when doing HTML5 routing: you should fix  that up with your own mapping (dynamic routing is completely unconcerned with and undefined for URLs...it is about a UI concern, not a browser concern). 

THis is also how you deal with aliasing. E.g. you move a page within your code structure, and you want URL "/a/b" to become "/c/d". During startup you simply have a map:

```
{"" ["landing-page"]
 "/a/b" ["route" "to" "c" "d"]
 ...}
```

The *convenience* of being able to, for the most part, split a URL into strings is just that: a convenience, not the core definition and integration with URLs.
